### ISSUE TITLE
SeeedStudio ReSpeaker Mic Array v2.0

### ISSUE THREAD

**Issue by kyvaith** [formatBCE/Respeaker-Lite-ESPHome-integration#18]
Hi, I have SeeedStudio ReSpeaker Mic Array v2.0. Is it possible to use this code by combining it with some ESP32? If so, how?

**Comment by formatBCE** [comment]
Sorry, I don't think so. That board has USB connectivity exclusively, and doesn't bind to I2S protocol (thus ESP).
