### ISSUE TITLE
In process binary sensor deprecated

### ISSUE THREAD

**Issue by rananna** [formatBCE/Respeaker-Lite-ESPHome-integration#19]
You are most likely aware of this, but just in case:

Repair issue
Warning ⸱ Reported by ESPHome
This stops working in version 2025.4. Please address before upgrading.

The ESPHome in progress binary sensor binary_sensor.respeaker_satellite_assist_in_progress is deprecated.

Migrate your configuration to use the corresponding assist_satellite entity and then click SUBMIT to disable the in progress binary sensor and fix this issue.

**Comment by formatBCE** [comment]
There's nothing to do on my side. This sensor is created by HA automatically for every satellite. Disable it and forget. :)
