### ISSUE TITLE
Difference between home-assistant-voice-pe

### ISSUE THREAD

**Issue by kyvaith** [formatBCE/Respeaker-Lite-ESPHome-integration#21]
Hi, I noticed that the file at https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml has over 1,000 more lines of code compared to your version. Could you explain the reason for this? Are there any features or functionalities missing in your version as a result?

Thanks!

**Comment by formatBCE** [comment]
You may compare files to see what is missing. :)

Mostly it's LED logic. PE has ring of 12 LEDs, and they have a heck of animations there, and that things are enormous in code. 
Also there's some multi-click logic like Easter egg Morse code, that starts some sound/light sequence... I didn't include all that stuff, and took LED logic from my previous project on generic esp32s3 Devkit-C.

If you find something you want to add from PE YAML - feel free to make PR. It's open source all in all :)
