### ISSUE TITLE
Error updating firmware

### ISSUE THREAD

**Issue by wsieber** [formatBCE/Respeaker-Lite-ESPHome-integration#22]
Hello,

I recieve the Invalid DFU suffix signature, and then the firmware updarte hangs at 96% and gives me the error at the bottom of the included terminal input. Dfu-util sees the device as it should. Any ideas on where should I be looking?

Thanks,

Willie

PS C:\Users\Willie> dfu-util -R -e -a 1 -D D:\dfu-util-0.11-binaries\win64\respeaker_lite_i2s_dfu_firmware_48k_v1.0.9.bin
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Warning: Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release
Opening DFU capable USB device...
Device ID 2886:0019
Device DFU version 0101
Claiming USB DFU Interface...
Setting Alternate Interface #1 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 0101
Device returned transfer size 4096
Copying data from PC to DFU device
Download        [======================== ]  96%       286720 bytesError during download get_status (LIBUSB_ERROR_TIMEOUT)

**Comment by formatBCE** [comment]
IDK what it got to do with this repository tho. :)
I use DFU util on Mac, and never had any trouble - probably re-downloading bin file would help, but if it's not - I'd suggest trying Linux or Mac.
